# Site wide configuration

title:            大胖熊的窝
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Carter
  avatar: profile\profile.jpg
  bio: "Android Software Developer. Like tech, food and my girlfriend."
  email: tongtong68@gmail.com
  disqus-shortname: 
  twitter: #https://twitter.com/tongtong68
  facebook: #https://www.facebook.com/tong.peng.33
  google:
    plus: #https://plus.google.com/u/0/113081040045711761036/posts
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #https://github.com/tongtong68
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #https://instagram.com/tongtong68
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #大胖熊起飞吧
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
